=== api-evangelist/amazon-mediatailor/json-schema/mediatailor-api-put-playback-configuration-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-mediatailor/refs/heads/main/json-schema/mediatailor-api-put-playback-configuration-request-schema.json",
  "title": "PutPlaybackConfigurationRequest",
  "description": "PutPlaybackConfigurationRequest schema from Amazon MediaTailor API",
  "type": "object",
  "properties": {
    "AdDecisionServerUrl": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "The URL for the ad decision server (ADS). This includes the specification of static parameters and placeholders for dynamic parameters. AWS Elemental MediaTailor substitutes player-specific and session-specific parameters as needed when calling the ADS. Alternately, for testing you can provide a static VAST URL. The maximum length is 25,000 characters."
        }
      ]
    },
    "AvailSuppression": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AvailSuppression"
        },
        {
          "description": "The configuration for avail suppression, also known as ad suppression. For more information about ad suppression, see <a href=\"https://docs.aws.amazon.com/mediatailor/latest/ug/ad-behavior.html\">Ad Suppression</a>."
        }
      ]
    },
    "Bumper": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Bumper"
        },
        {
          "description": "The configuration for bumpers. Bumpers are short audio or video clips that play at the start or before the end of an ad break. To learn more about bumpers, see <a href=\"https://docs.aws.amazon.com/mediatailor/latest/ug/bumpers.html\">Bumpers</a>."
        }
      ]
    },
    "CdnConfiguration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CdnConfiguration"
        },
        {
          "description": "The configuration for using a content delivery network (CDN), like Amazon CloudFront, for content and ad segment management."
        }
      ]
    },
    "ConfigurationAliases": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ConfigurationAliasesRequest"
        },
        {
          "description": "The player parameters and aliases used as dynamic variables during session initialization. For more information, see <a href=\"https://docs.aws.amazon.com/mediatailor/latest/ug/variables-domain.html\">Domain Variables</a>."
        }
      ]
    },
    "DashConfiguration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DashConfigurationForPut"
        },
        {
          "description": "The configuration for DASH content."
        }
      ]
    },
    "LivePreRollConfiguration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LivePreRollConfiguration"
        },
        {
          "description": "The configuration for pre-roll ad insertion."
        }
      ]
    },
    "ManifestProcessingRules": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ManifestProcessingRules"
        },
        {
          "description": "The configuration for manifest processing rules. Manifest processing rules enable customization of the personalized manifests created by MediaTailor."
        }
      ]
    },
    "Name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "The identifier for the playback configuration."
        }
      ]
    },
    "PersonalizationThresholdSeconds": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__integerMin1"
        },
        {
          "description": "Defines the maximum duration of underfilled ad time (in seconds) allowed in an ad break. If the duration of underfilled ad time exceeds the personalization threshold, then the personalization of the ad break is abandoned and the underlying content is shown. This feature applies to <i>ad replacement</i> in live and VOD streams, rather than ad insertion, because it relies on an underlying content stream. For more information about ad break behavior, including ad replacement and insertion, see <a href=\"https://docs.aws.amazon.com/mediatailor/latest/ug/ad-behavior.html\">Ad Behavior in AWS Elemental MediaTailor</a>."
        }
      ]
    },
    "SlateAdUrl": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "The URL for a high-quality video asset to transcode and use to fill in time that's not used by ads. AWS Elemental MediaTailor shows the slate to fill in gaps in media content. Configuring the slate is optional for non-VPAID configurations. For VPAID, the slate is required because MediaTailor provides it in the slots that are designated for dynamic ad content. The slate must be a high-quality asset that contains both audio and video."
        }
      ]
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__mapOf__string"
        },
        {
          "xml": {
            "name": "tags"
          },
          "description": "The tags to assign to the playback configuration. Tags are key-value pairs that you can associate with Amazon resources to help with organization, access control, and cost tracking. For more information, see <a href=\"https://docs.aws.amazon.com/mediatailor/latest/ug/tagging.html\">Tagging AWS Elemental MediaTailor Resources</a>."
        }
      ]
    },
    "TranscodeProfileName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "The name that is used to associate this playback configuration with a custom transcode profile. This overrides the dynamic transcoding defaults of MediaTailor. Use this only if you have already set up custom profiles with the help of AWS Support."
        }
      ]
    },
    "VideoContentSourceUrl": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "The URL prefix for the parent manifest for the stream, minus the asset ID. The maximum length is 512 characters."
        }
      ]
    }
  },
  "required": [
    "Name"
  ]
}

=== api-evangelist/amazon-mediatailor/examples/mediatailor-api-put-playback-configuration-request-example.json
{
  "AdDecisionServerUrl": "example-value",
  "AvailSuppression": "example-value",
  "Bumper": "example-value",
  "CdnConfiguration": "example-value",
  "ConfigurationAliases": "example-value",
  "DashConfiguration": "example-value",
  "LivePreRollConfiguration": "example-value",
  "ManifestProcessingRules": "example-value",
  "Name": "example-resource",
  "PersonalizationThresholdSeconds": "example-value",
  "SlateAdUrl": "example-value",
  "Tags": "example-value",
  "TranscodeProfileName": "example-resource",
  "VideoContentSourceUrl": "id-abc123"
}
