=== api-evangelist/amazon-mediatailor/json-schema/mediatailor-api-describe-live-source-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-mediatailor/refs/heads/main/json-schema/mediatailor-api-describe-live-source-response-schema.json",
  "title": "DescribeLiveSourceResponse",
  "description": "DescribeLiveSourceResponse schema from Amazon MediaTailor API",
  "type": "object",
  "properties": {
    "Arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "The ARN of the live source."
        }
      ]
    },
    "CreationTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__timestampUnix"
        },
        {
          "description": "The timestamp that indicates when the live source was created."
        }
      ]
    },
    "HttpPackageConfigurations": {
      "allOf": [
        {
          "$ref": "#/components/schemas/HttpPackageConfigurations"
        },
        {
          "description": "The HTTP package configurations."
        }
      ]
    },
    "LastModifiedTime": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__timestampUnix"
        },
        {
          "description": "The timestamp that indicates when the live source was modified."
        }
      ]
    },
    "LiveSourceName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "The name of the live source."
        }
      ]
    },
    "SourceLocationName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__string"
        },
        {
          "description": "The name of the source location associated with the live source."
        }
      ]
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/__mapOf__string"
        },
        {
          "xml": {
            "name": "tags"
          },
          "description": "The tags assigned to the live source. Tags are key-value pairs that you can associate with Amazon resources to help with organization, access control, and cost tracking. For more information, see <a href=\"https://docs.aws.amazon.com/mediatailor/latest/ug/tagging.html\">Tagging AWS Elemental MediaTailor Resources</a>."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-mediatailor/examples/mediatailor-api-create-live-source-response-example.json
{
  "Arn": "arn:aws:service:us-east-1:123456789012:resource/example",
  "CreationTime": "example-value",
  "HttpPackageConfigurations": "example-value",
  "LastModifiedTime": "example-value",
  "LiveSourceName": "example-resource",
  "SourceLocationName": "example-resource",
  "Tags": "example-value"
}
